openapi: 3.1.0
info:
    title: Petstore API
    description: |-
        A sample Pet Store API demonstrating go-specgen features.
        This API allows you to manage pets in a store with full CRUD operations.
    termsOfService: https://petstore.example.com/terms
    contact:
        name: API Support
        url: https://petstore.example.com/support
        email: support@petstore.example.com
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
    version: 1.0.0
servers:
    - url: https://api.petstore.example.com
      description: Production server
    - url: https://staging.petstore.example.com
      description: Staging server
paths:
    /pets:
        get:
            tags:
                - pets
            summary: List all pets
            description: Returns a paginated list of pets with optional filtering by status, category, and tags.
            operationId: listPets
            parameters:
                - name: limit
                  in: query
                  description: Maximum results to return
                  required: true
                  schema:
                    type:
                        - integer
                        - "null"
                    maximum: 100
                    minimum: 1
                    default: 20
                - name: offset
                  in: query
                  description: Offset for pagination
                  required: true
                  schema:
                    type:
                        - integer
                        - "null"
                    minimum: 0
                    default: 0
                - name: status
                  in: query
                  description: Filter by status
                  required: true
                  schema:
                    type:
                        - string
                        - "null"
                    enum:
                        - available
                        - pending
                        - sold
                - name: category
                  in: query
                  description: Filter by category
                  required: true
                  schema:
                    type:
                        - string
                        - "null"
                    enum:
                        - dog
                        - cat
                        - bird
                        - fish
                        - other
                - name: tags
                  in: query
                  description: Filter by tags (can specify multiple)
                  required: true
                  schema:
                    type: array
                    items:
                        type: string
            responses:
                "200":
                    description: Successful response with list of pets
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Pet'
                "400":
                    description: Invalid query parameters
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - pets
            summary: Create a new pet
            description: Creates a new pet in the store.
            operationId: createPet
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreatePetRequest'
                required: true
            responses:
                "201":
                    description: Pet created successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pet'
                "400":
                    description: Invalid request body
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /pets/{id}:
        get:
            tags:
                - pets
            summary: Get a pet by ID
            description: Returns a single pet by its unique identifier.
            operationId: getPet
            parameters:
                - name: id
                  in: path
                  description: Pet ID
                  required: true
                  schema:
                    type: integer
                    format: int64
            responses:
                "200":
                    description: Successful response with pet details
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pet'
                "404":
                    description: Pet not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - pets
            summary: Update a pet
            description: Updates an existing pet's information.
            operationId: updatePet
            parameters:
                - name: id
                  in: path
                  description: Pet ID
                  required: true
                  schema:
                    type: integer
                    format: int64
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdatePetRequest'
                required: true
            responses:
                "404":
                    description: Pet not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                "200":
                    description: Pet updated successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Pet'
                "400":
                    description: Invalid request body
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
        delete:
            tags:
                - pets
            summary: Delete a pet
            description: Removes a pet from the store permanently.
            operationId: deletePet
            parameters:
                - name: id
                  in: path
                  description: Pet ID
                  required: true
                  schema:
                    type: integer
                    format: int64
            responses:
                "204":
                    description: Pet deleted successfully
                "404":
                    description: Pet not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
    /store/inventory:
        get:
            tags:
                - store
            summary: Get store inventory
            description: |-
                Returns a map of status codes to quantities.
                This endpoint is deprecated and will be removed in a future version.
            operationId: getInventory
            responses:
                "200":
                    description: Inventory counts by status
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties:
                                    type: integer
            deprecated: true
components:
    schemas:
        Pet:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    description: Unique identifier
                    example: 12345
                name:
                    type: string
                    maxLength: 100
                    minLength: 1
                    description: Pet name
                    example: Fluffy
                category:
                    type: string
                    enum:
                        - dog
                        - cat
                        - bird
                        - fish
                        - other
                    description: Pet category
                    example: dog
                status:
                    type: string
                    enum:
                        - available
                        - pending
                        - sold
                    description: Pet availability status
                    default: available
                tags:
                    type: array
                    items:
                        type: string
                    description: Pet tags for searching
                age:
                    type:
                        - integer
                        - "null"
                    maximum: 100
                    minimum: 0
                    description: Pet age in years
                created_at:
                    type: string
                    format: date-time
                    description: When the pet was added to the store
                updated_at:
                    type: string
                    format: date-time
                    description: When the pet was last updated
            required:
                - id
                - name
                - category
                - status
                - tags
                - created_at
                - updated_at
            description: A pet available in the store
        CreatePetRequest:
            type: object
            properties:
                name:
                    type: string
                    maxLength: 100
                    minLength: 1
                    description: Pet name
                category:
                    type: string
                    enum:
                        - dog
                        - cat
                        - bird
                        - fish
                        - other
                    description: Pet category
                status:
                    type:
                        - string
                        - "null"
                    enum:
                        - available
                        - pending
                    description: Initial status
                    default: available
                tags:
                    type: array
                    items:
                        type: string
                    description: Pet tags for searching
                age:
                    type:
                        - integer
                        - "null"
                    maximum: 100
                    minimum: 0
                    description: Pet age in years
            required:
                - name
                - category
        UpdatePetRequest:
            type: object
            properties:
                name:
                    type:
                        - string
                        - "null"
                    maxLength: 100
                    minLength: 1
                    description: Pet name
                category:
                    type:
                        - string
                        - "null"
                    enum:
                        - dog
                        - cat
                        - bird
                        - fish
                        - other
                    description: Pet category
                status:
                    type:
                        - string
                        - "null"
                    enum:
                        - available
                        - pending
                        - sold
                    description: Pet status
                tags:
                    type: array
                    items:
                        type: string
                    description: Pet tags for searching
                age:
                    type:
                        - integer
                        - "null"
                    maximum: 100
                    minimum: 0
                    description: Pet age in years
        Error:
            type: object
            properties:
                code:
                    type: string
                    description: Error code
                message:
                    type: string
                    description: Human-readable error message
                details:
                    type: array
                    items:
                        type: string
                    description: Additional error details
            required:
                - code
                - message
            description: Standard error response
    securitySchemes:
        bearerAuth:
            type: http
            description: JWT token authentication
            scheme: bearer
            bearerFormat: JWT
security:
    - bearerAuth: []
tags:
    - name: pets
      description: Pet management operations
    - name: store
      description: Store operations
