openapi: 3.1.0
info:
    title: Skipped
    version: 1.0.0
paths:
    /gadgets:
        get:
            responses:
                "200":
                    description: ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Gadget'
components:
    schemas:
        Gadget:
            type: object
            properties:
                id:
                    type: string
                    description: Gadget ID
            required:
                - id
